// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvDOQwBik0F_idzT_sp23aYCGav1HVYc',
    appId: '1:976132713934:web:b4a265341b8652f9ba8f9f',
    messagingSenderId: '976132713934',
    projectId: 'flutter-firebase-example-9d38f',
    authDomain: 'flutter-firebase-example-9d38f.firebaseapp.com',
    storageBucket: 'flutter-firebase-example-9d38f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEPx7OaSutWvPb8eXJ2VZhHYupEOcX0eo',
    appId: '1:976132713934:android:5bbdd9e04505d62cba8f9f',
    messagingSenderId: '976132713934',
    projectId: 'flutter-firebase-example-9d38f',
    storageBucket: 'flutter-firebase-example-9d38f.appspot.com',
  );
}
